# Generated by Django 5.2 on 2025-07-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True)),
                ('company', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contract', 'Contract'), ('Internship', 'Internship')], max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('bonus_skills', models.TextField(blank=True, null=True)),
                ('required_skills', models.TextField(help_text='Comma-separeted list of required tech skills, e.g. JavaScripts, Python, GitHub', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Clossing_date', models.DateField(null=True)),
            ],
        ),
    ]
