# Generated by Django 5.2 on 2025-07-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='Clossing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
