# Generated by Django 5.2 on 2025-07-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobpost_clossing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separeted list of required tech skills, e.g. JavaScripts, Python, GitHub', null=True),
        ),
    ]
