# Generated by Django 5.2 on 2025-07-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('resumes', '0002_resume_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobpost'),
        ),
    ]
